include ../Makefile

all: exceptions invariants static-assertions

exceptions: exceptions.cpp
	$(CC) $@.cpp -o $@

invariants: invariants.cpp
	$(CC) $@.cpp -o $@

static-assertions: static-assertions.cpp
	$(CC) $@.cpp -o $@
