all: main function-templates function-objects

include ../../Makefile

main: main.cpp
	$(CC) $@.cpp -o $@

function-templates: function-templates.cpp
	$(CC) $@.cpp -o $@

function-objects: function-objects.cpp
	$(CC) $@.cpp -o $@

lambdas: lambdas.cpp
	$(CC) $@.cpp -o $@
